In [ ]:
import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
file_path = "Student Awareness Survey (Responses) - Form Responses 1.csv"
df = pd.read_csv(file_path)

df.head()

,Timestamp,Registration Number,Email,Job role that you are interested in,What is the minimum salary of students placed through campus (In LPA..respond as a number),What is the maximum salary of students placed through campus (In LPA..respond as a number),What is the median salary of students placed through campus (In LPA..respond as a number),Which is the highest paying company that recruits from campus?,Rate your contribution towards extra curricular activities,Rate your technical competencies,What are your package expectations (LPA),Your CIA % of last semester,Your GPA of last semester,Your maximum attendance % till last semester,Internships Interests
0,6/15/2026 9:25:39,2547231,kunnal.kunnal@mca.christuniversity.in,Software Development Engineer (SDE),3.5,12,6.8,Akasa air,4.0,3.0,8,69,3.40,98,"AI/ML, Web Development, Data Science/Analytics..."
1,6/15/2026 9:53:54,2547237,omkaar.chakraborty@mca.christuniversity.in,Software Development Engineer (SDE),6,20,10,Fractal,4.0,4.0,12,75,3.69,95,"Web Development, DevOps/Cloud Computing, Mobil..."
2,6/15/2026 9:54:56,2547203,abhinav.jain@mca.christuniversity.in,Full Stack Developer,4,12,6.3,Akasa Air,5.0,4.0,12,82,3.41,95,"AI/ML, Web Development, Mobile App Development"
3,6/15/2026 9:55:17,2547228,jai.pareek@mca.christuniversity.in,Full Stack Developer,600000,1400000,800000,Akasa airlines,5.0,4.0,1200000,91,3.60,92,"Web Development, DevOps/Cloud Computing, Cyber..."
4,6/15/2026 9:55:42,2547241,r.karan@mca.christuniversity.in,Software Development Engineer (SDE),4,4,6,12,2.0,3.0,12,70,3.54,93,"AI/ML, Data Science/Analytics"

In [ ]:
print("Shape:", df.shape)
print("\nColumns:\n", df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Shape: (50, 15)

Columns:
 ['Timestamp', 'Registration Number', 'Email', 'Job role that you are interested in', 'What is the minimum salary of students placed through campus (In LPA..respond as a number)', 'What is the maximum salary of students placed through campus (In LPA..respond as a number)', 'What is the median salary of students placed through campus (In LPA..respond as a number)', 'Which is the highest paying company that recruits from campus?', 'Rate your contribution towards extra curricular activities', 'Rate your technical competencies', 'What are your package expectations (LPA)', 'Your CIA % of last semester', 'Your GPA of last semester', 'Your maximum attendance % till last semester', 'Internships Interests']

First 5 rows:

,Timestamp,Registration Number,Email,Job role that you are interested in,What is the minimum salary of students placed through campus (In LPA..respond as a number),What is the maximum salary of students placed through campus (In LPA..respond as a number),What is the median salary of students placed through campus (In LPA..respond as a number),Which is the highest paying company that recruits from campus?,Rate your contribution towards extra curricular activities,Rate your technical competencies,What are your package expectations (LPA),Your CIA % of last semester,Your GPA of last semester,Your maximum attendance % till last semester,Internships Interests
0,6/15/2026 9:25:39,2547231,kunnal.kunnal@mca.christuniversity.in,Software Development Engineer (SDE),3.5,12,6.8,Akasa air,4.0,3.0,8,69,3.40,98,"AI/ML, Web Development, Data Science/Analytics..."
1,6/15/2026 9:53:54,2547237,omkaar.chakraborty@mca.christuniversity.in,Software Development Engineer (SDE),6,20,10,Fractal,4.0,4.0,12,75,3.69,95,"Web Development, DevOps/Cloud Computing, Mobil..."
2,6/15/2026 9:54:56,2547203,abhinav.jain@mca.christuniversity.in,Full Stack Developer,4,12,6.3,Akasa Air,5.0,4.0,12,82,3.41,95,"AI/ML, Web Development, Mobile App Development"
3,6/15/2026 9:55:17,2547228,jai.pareek@mca.christuniversity.in,Full Stack Developer,600000,1400000,800000,Akasa airlines,5.0,4.0,1200000,91,3.60,92,"Web Development, DevOps/Cloud Computing, Cyber..."
4,6/15/2026 9:55:42,2547241,r.karan@mca.christuniversity.in,Software Development Engineer (SDE),4,4,6,12,2.0,3.0,12,70,3.54,93,"AI/ML, Data Science/Analytics"

Missing values:
Timestamp                                                                                     0
Registration Number                                                                           0
Email                                                                                         0
Job role that you are interested in                                                           0
What is the minimum salary of students placed through campus (In LPA..respond as a number)    0
What is the maximum salary of students placed through campus (In LPA..respond as a number)    0
What is the median salary of students placed through campus (In LPA..respond as a number)     0
Which is the highest paying company that recruits from campus?                                1
Rate your contribution towards extra curricular activities                                    1
Rate your technical competencies                                                              1
What are your package expectations (LPA)                                                      1
Your CIA % of last semester                                                                   0
Your GPA of last semester                                                                     0
Your maximum attendance % till last semester                                                  0
Internships Interests                                                                         1
dtype: int64

Duplicate rows: 0

In [ ]:
df = df.drop_duplicates().copy()

# Strip spaces from column names if any
df.columns = df.columns.str.strip()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (50, 15)

In [ ]:
# Remove duplicates and clean missing values
numeric_cols = [
    'What is the minimum salary of students placed through campus (In LPA..respond as a number)',
    'What is the maximum salary of students placed through campus (In LPA..respond as a number)',
    'What is the median salary of students placed through campus (In LPA..respond as a number)',
    'Rate your contribution towards extra curricular activities',
    'Rate your technical competencies',
    'What are your package expectations (LPA)',
    'Your CIA % of last semester',
    'Your GPA of last semester',
    'Your maximum attendance % till last semester'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

print(df[numeric_cols].dtypes)

What is the minimum salary of students placed through campus (In LPA..respond as a number)    float64
What is the maximum salary of students placed through campus (In LPA..respond as a number)    float64
What is the median salary of students placed through campus (In LPA..respond as a number)     float64
Rate your contribution towards extra curricular activities                                    float64
Rate your technical competencies                                                              float64
What are your package expectations (LPA)                                                      float64
Your CIA % of last semester                                                                   float64
Your GPA of last semester                                                                     float64
Your maximum attendance % till last semester                                                  float64
dtype: object

In [ ]:
# Handle missing numeric values
# Drop rows where the important regression columns are missing
needed_cols = [
    'Your CIA % of last semester',
    'Your GPA of last semester',
    'Your maximum attendance % till last semester'
]

df_clean = df.dropna(subset=needed_cols).copy()

# Optional: fill other numeric columns with median if needed
for col in numeric_cols:
    if col in df_clean.columns:
        df_clean[col] = df_clean[col].fillna(df_clean[col].median())

print("Shape after cleaning:", df_clean.shape)
print("\nMissing values after cleaning:")
print(df_clean[needed_cols].isnull().sum())

Shape after cleaning: (39, 15)

Missing values after cleaning:
Your CIA % of last semester                     0
Your GPA of last semester                       0
Your maximum attendance % till last semester    0
dtype: int64

In [ ]:
# Statistical summary
display(df_clean.describe())

display(df_clean[needed_cols].describe())

,Registration Number,What is the minimum salary of students placed through campus (In LPA..respond as a number),What is the maximum salary of students placed through campus (In LPA..respond as a number),What is the median salary of students placed through campus (In LPA..respond as a number),Rate your contribution towards extra curricular activities,Rate your technical competencies,What are your package expectations (LPA),Your CIA % of last semester,Your GPA of last semester,Your maximum attendance % till last semester
count,3.900000e+01,39.000000,3.900000e+01,39.000000,39.000000,39.000000,3.900000e+01,39.000000,39.000000,39.000000
mean,2.547231e+06,32055.533333,9.744751e+04,58980.712821,3.435897,3.487179,8.719035e+04,72.546667,3.418974,94.218974
std,1.715862e+01,118368.878088,3.429614e+05,207385.335911,1.252258,0.756439,3.196839e+05,5.968592,0.207413,3.778685
min,2.547201e+06,3.000000,4.000000e+00,3.000000,1.000000,2.000000,-8.000000e+00,60.000000,3.000000,85.000000
25%,2.547217e+06,4.000000,1.200000e+01,6.000000,3.000000,3.000000,8.000000e+00,69.890000,3.325000,92.500000
50%,2.547232e+06,4.000000,1.200000e+01,6.700000,4.000000,3.000000,1.000000e+01,71.780000,3.400000,95.000000
75%,2.547242e+06,6.000000,1.350000e+01,7.500000,4.000000,4.000000,1.200000e+01,75.600000,3.575000,96.270000
max,2.547262e+06,600000.000000,1.400000e+06,800000.000000,5.000000,5.000000,1.500000e+06,91.000000,3.790000,100.000000

,Your CIA % of last semester,Your GPA of last semester,Your maximum attendance % till last semester
count,39.000000,39.000000,39.000000
mean,72.546667,3.418974,94.218974
std,5.968592,0.207413,3.778685
min,60.000000,3.000000,85.000000
25%,69.890000,3.325000,92.500000
50%,71.780000,3.400000,95.000000
75%,75.600000,3.575000,96.270000
max,91.000000,3.790000,100.000000

In [ ]:
#Helper function for manual OLS
def manual_ols(x, y):
    """
    Compute slope and intercept using Ordinary Least Squares:
    slope = sum((x - x_mean)(y - y_mean)) / sum((x - x_mean)^2)
    intercept = y_mean - slope * x_mean
    """
    x = np.array(x).flatten()
    y = np.array(y).flatten()

    x_mean = np.mean(x)
    y_mean = np.mean(y)

    numerator = np.sum((x - x_mean) * (y - y_mean))
    denominator = np.sum((x - x_mean) ** 2)

    slope = numerator / denominator
    intercept = y_mean - slope * x_mean

    return slope, intercept

def run_regression(df_data, x_col, y_col, experiment_name):
    print("=" * 80)
    print(experiment_name)
    print("=" * 80)

    # Select only required columns and remove missing values
    data = df_data[[x_col, y_col]].dropna().copy()

    X = data[[x_col]].values
    y = data[y_col].values

    # Split into train and test sets
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # Scikit-learn regression
    model = LinearRegression()
    model.fit(X_train, y_train)

    sklearn_slope = model.coef_[0]
    sklearn_intercept = model.intercept_

    y_pred_sklearn = model.predict(X_test)

    # Manual OLS using training set
    manual_slope, manual_intercept = manual_ols(X_train, y_train)
    y_pred_manual = manual_slope * X_test.flatten() + manual_intercept

    # Metrics
    mae_sklearn = mean_absolute_error(y_test, y_pred_sklearn)
    mse_sklearn = mean_squared_error(y_test, y_pred_sklearn)
    rmse_sklearn = np.sqrt(mse_sklearn)
    r2_sklearn = r2_score(y_test, y_pred_sklearn)

    mae_manual = mean_absolute_error(y_test, y_pred_manual)
    mse_manual = mean_squared_error(y_test, y_pred_manual)
    rmse_manual = np.sqrt(mse_manual)
    r2_manual = r2_score(y_test, y_pred_manual)

    # Comparison
    diff = np.abs(y_pred_sklearn - y_pred_manual)

    result = {
        "experiment": experiment_name,
        "x_col": x_col,
        "y_col": y_col,
        "sklearn_slope": sklearn_slope,
        "sklearn_intercept": sklearn_intercept,
        "manual_slope": manual_slope,
        "manual_intercept": manual_intercept,
        "X_test": X_test.flatten(),
        "y_test": y_test,
        "y_pred_sklearn": y_pred_sklearn,
        "y_pred_manual": y_pred_manual,
        "abs_diff": diff,
        "metrics": {
            "sklearn": {"MAE": mae_sklearn, "MSE": mse_sklearn, "RMSE": rmse_sklearn, "R2": r2_sklearn},
            "manual": {"MAE": mae_manual, "MSE": mse_manual, "RMSE": rmse_manual, "R2": r2_manual},
        }
    }

    print("\nScikit-learn parameters")
    print("Slope:", sklearn_slope)
    print("Intercept:", sklearn_intercept)

    print("\nManual OLS parameters")
    print("Slope:", manual_slope)
    print("Intercept:", manual_intercept)

    print("\nComparison of predictions (first 10 rows)")
    comparison_df = pd.DataFrame({
        x_col: X_test.flatten(),
        "Actual_GPA": y_test,
        "Pred_Scikit": y_pred_sklearn,
        "Pred_Manual": y_pred_manual,
        "Abs_Diff": diff
    })
    display(comparison_df.head(10))

    print("\nAverage absolute difference:", diff.mean())
    print("Maximum absolute difference:", diff.max())

    print("\nScikit-learn metrics:", result["metrics"]["sklearn"])
    print("Manual OLS metrics:", result["metrics"]["manual"])

    return result

In [ ]:
# Experiment 1 — CIA % can predict GPA
cia_col = 'Your CIA % of last semester'
gpa_col = 'Your GPA of last semester'

result_cia = run_regression(
    df_clean,
    x_col=cia_col,
    y_col=gpa_col,
    experiment_name="Experiment 1: CIA % -> GPA"
)

================================================================================
Experiment 1: CIA % -> GPA
================================================================================

Scikit-learn parameters
Slope: 0.01652616755411487
Intercept: 2.2121674902659123

Manual OLS parameters
Slope: 0.016526167554114873
Intercept: 2.2121674902659123

Comparison of predictions (first 10 rows)

,Your CIA % of last semester,Actual_GPA,Pred_Scikit,Pred_Manual,Abs_Diff
0,75.2,3.54,3.454935,3.454935,4.440892e-16
1,75.0,3.66,3.451630,3.451630,4.440892e-16
2,70.0,3.54,3.368999,3.368999,0.000000e+00
3,70.0,3.49,3.368999,3.368999,0.000000e+00
4,67.0,3.46,3.319421,3.319421,4.440892e-16
5,80.0,3.12,3.534261,3.534261,4.440892e-16
6,74.0,3.40,3.435104,3.435104,0.000000e+00
7,70.0,3.40,3.368999,3.368999,0.000000e+00

Average absolute difference: 2.220446049250313e-16
Maximum absolute difference: 4.440892098500626e-16

Scikit-learn metrics: {'MAE': 0.1507976328940211, 'MSE': 0.03601305616934358, 'RMSE': np.float64(0.18977106251835021), 'R2': -0.638004118284407}
Manual OLS metrics: {'MAE': 0.15079763289402098, 'MSE': 0.03601305616934358, 'RMSE': np.float64(0.18977106251835021), 'R2': -0.638004118284407}

In [ ]:
# Experiment 2 — Attendance % can predict GPA
attendance_col = 'Your maximum attendance % till last semester'

result_attendance = run_regression(
    df_clean,
    x_col=attendance_col,
    y_col=gpa_col,
    experiment_name="Experiment 2: Attendance % -> GPA"
)

================================================================================
Experiment 2: Attendance % -> GPA
================================================================================

Scikit-learn parameters
Slope: 0.014862437825207275
Intercept: 2.0128376781643604

Manual OLS parameters
Slope: 0.014862437825207273
Intercept: 2.012837678164361

Comparison of predictions (first 10 rows)

,Your maximum attendance % till last semester,Actual_GPA,Pred_Scikit,Pred_Manual,Abs_Diff
0,96.0,3.54,3.439632,3.439632,4.440892e-16
1,95.0,3.66,3.424769,3.424769,4.440892e-16
2,93.0,3.54,3.395044,3.395044,4.440892e-16
3,100.0,3.49,3.499081,3.499081,4.440892e-16
4,95.0,3.46,3.424769,3.424769,4.440892e-16
5,92.0,3.12,3.380182,3.380182,0.000000e+00
6,94.0,3.40,3.409907,3.409907,4.440892e-16
7,94.0,3.40,3.409907,3.409907,4.440892e-16

Average absolute difference: 3.885780586188048e-16
Maximum absolute difference: 4.440892098500626e-16

Scikit-learn metrics: {'MAE': 0.10060780472815084, 'MSE': 0.01945425446218993, 'RMSE': np.float64(0.13947850896173908), 'R2': 0.11515010618992594}
Manual OLS metrics: {'MAE': 0.10060780472815078, 'MSE': 0.019454254462189874, 'RMSE': np.float64(0.13947850896173888), 'R2': 0.11515010618992838}

In [ ]:
# Display both experiments side by side
summary = pd.DataFrame([
    {
        "Experiment": "CIA % -> GPA",
        "Sklearn Slope": result_cia["sklearn_slope"],
        "Sklearn Intercept": result_cia["sklearn_intercept"],
        "Manual Slope": result_cia["manual_slope"],
        "Manual Intercept": result_cia["manual_intercept"],
        "Avg Abs Diff": result_cia["abs_diff"].mean(),
        "Max Abs Diff": result_cia["abs_diff"].max(),
        "Sklearn R2": result_cia["metrics"]["sklearn"]["R2"],
        "Manual R2": result_cia["metrics"]["manual"]["R2"],
    },
    {
        "Experiment": "Attendance % -> GPA",
        "Sklearn Slope": result_attendance["sklearn_slope"],
        "Sklearn Intercept": result_attendance["sklearn_intercept"],
        "Manual Slope": result_attendance["manual_slope"],
        "Manual Intercept": result_attendance["manual_intercept"],
        "Avg Abs Diff": result_attendance["abs_diff"].mean(),
        "Max Abs Diff": result_attendance["abs_diff"].max(),
        "Sklearn R2": result_attendance["metrics"]["sklearn"]["R2"],
        "Manual R2": result_attendance["metrics"]["manual"]["R2"],
    }
])

display(summary)

,Experiment,Sklearn Slope,Sklearn Intercept,Manual Slope,Manual Intercept,Avg Abs Diff,Max Abs Diff,Sklearn R2,Manual R2
0,CIA % -> GPA,0.016526,2.212167,0.016526,2.212167,2.220446e-16,4.440892e-16,-0.638004,-0.638004
1,Attendance % -> GPA,0.014862,2.012838,0.014862,2.012838,3.885781e-16,4.440892e-16,0.115150,0.115150

In [ ]:
# Save learned parameters using Pickle
weights = {
    "cia_to_gpa": {
        "slope": result_cia["manual_slope"],
        "intercept": result_cia["manual_intercept"]
    },
    "attendance_to_gpa": {
        "slope": result_attendance["manual_slope"],
        "intercept": result_attendance["manual_intercept"]
    }
}

pickle_file = "linear_regression_weights.pkl"

with open(pickle_file, "wb") as f:
    pickle.dump(weights, f)

print(f"Saved parameters to {pickle_file}")

Saved parameters to linear_regression_weights.pkl

In [ ]:
# Load the Pickle file and verify
with open("linear_regression_weights.pkl", "rb") as f:
    loaded_weights = pickle.load(f)

loaded_weights

{'cia_to_gpa': {'slope': np.float64(0.016526167554114873),
  'intercept': np.float64(2.2121674902659123)},
 'attendance_to_gpa': {'slope': np.float64(0.014862437825207273),
  'intercept': np.float64(2.012837678164361)}}

In [ ]:
# Use loaded parameters for prediction

# Example prediction using loaded parameters for CIA -> GPA
sample_cia = 75
cia_slope = loaded_weights["cia_to_gpa"]["slope"]
cia_intercept = loaded_weights["cia_to_gpa"]["intercept"]

predicted_gpa_cia = cia_slope * sample_cia + cia_intercept
print("Predicted GPA from CIA % =", predicted_gpa_cia)

# Example prediction using loaded parameters for Attendance -> GPA
sample_attendance = 85
att_slope = loaded_weights["attendance_to_gpa"]["slope"]
att_intercept = loaded_weights["attendance_to_gpa"]["intercept"]

predicted_gpa_att = att_slope * sample_attendance + att_intercept
print("Predicted GPA from Attendance % =", predicted_gpa_att)

Predicted GPA from CIA % = 3.451630056824528
Predicted GPA from Attendance % = 3.276144893306979

In [ ]:
# Final observations
print("Final Observations")
print("- Scikit-learn and manual OLS should give nearly identical slope and intercept values.")
print("- Small differences, if any, are usually due to floating-point precision.")
print("- Compare Avg Abs Diff and Max Abs Diff to confirm similarity.")
print("- Save the Pickle file after the final model parameters are learned.")

Final Observations
- Scikit-learn and manual OLS should give nearly identical slope and intercept values.
- Small differences, if any, are usually due to floating-point precision.
- Compare Avg Abs Diff and Max Abs Diff to confirm similarity.
- Save the Pickle file after the final model parameters are learned.